version: '3'

services:

    # Use latest Nginx to serve
    nginx:
        image: nginx:latest
        container_name: learn_laravel_nginx
        ports:
            - "8080:80"
        working_dir: /var/www
        volumes:
            - ./laravel:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network

    # Use latest PHP FPM to interpret
    php:
        image: php:fpm
        container_name: learn_laravel_php
        volumes:
            - ./laravel:/var/www
        networks:
            - code-network

    # Use latest MySQL for database
    mysql:
        image: mysql:latest
        container_name: learn_laravel_mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./dbdata:/var/lib/mysql/
        networks:
            - code-network

# Networks
networks:
    code-network:
        driver: bridge

# Volumes
volumes:
    dbdata:
        driver: local