version: '3'

services:

    ## Use latest Nginx to serve
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network

    ## Use latest PHP
    php:
        image: php:fpm
        volumes:
            - ./code:/var/www
        networks:
            - code-network

networks:
    code-network:
        driver: bridge